
elastic.max_background_threads=16
elastic.min_tp_threads=2
elastic.min_ap_threads=2
elastic.min_compaction_threads=4
elastic.max_tp_task_queue=131072
elastic.max_compaction_num=32

elastic.dbname=/tmp/ycsb-elastic
elastic.format=single
elastic.destroy=true

# Load options from file
elastic.optionsfile=elastic/options.ini

# Below options are ignored if options file is used
elastic.compression=snappy
elastic.max_background_jobs=2
elastic.target_file_size_base=67108864
elastic.target_file_size_multiplier=1
elastic.max_bytes_for_level_base=268435456
elastic.write_buffer_size=67108864
elastic.max_open_files=-1
elastic.max_write_buffer_number=10
elastic.use_direct_io_for_flush_compaction=false
elastic.use_direct_reads=false
elastic.allow_mmap_writes=false
elastic.allow_mmap_reads=false
elastic.cache_size=8388608
elastic.bloom_bits=0

# deprecated since rocksdb 8.0
elastic.compressed_cache_size=0

elastic.increase_parallelism=false
elastic.optimize_level_style_compaction=false